name: Code Check

on:
  pull_request:
    branches:
      - main

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Ruff check
        uses: astral-sh/ruff-action@v3
        with:
          src: "./src"
